require('plenary')

require("plugins.window-picker")
require("plugins.mason")
require("plugins.lsp")
require("plugins.blink")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.telescope")
require("plugins.todo-comments")
require("plugins.codecompanion")
require("plugins.treesitter")
require("plugins.render-markdown")
