require("nvim-treesitter").setup {
  ensure_installed = {
    'bash',
    'c',
    'cpp',
    'css',
    'diff',
    'dockerfile',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'goctl',
    'gomod',
    'gosum',
    'gotmpl',
    'gowork',
    'graphql',
    'html',
    'htmldjango',
    'http',
    'javascript',
    'jinja',
    'jinja_inline',
    'json',
    'jsx',
    'latex',
    'ledger',
    'llvm',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'markdown_inline',
    'mermaid',
    'powershell',
    'python',
    'regex',
    'rust',
    'sql',
    'ssh_config',
    'svelte',
    'systemverilog',
    'tcl',
    'toml',
    'typescript',
    'vhdl',
    'yaml',
    'zig',
}
}
local opt = vim.opt

opt.foldmethod = "expr"
opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
opt.foldenable = false
opt.foldlevelstart = 99
